name: tarea-3

services:
  mariadb:
    image: mariadb:lts-ubi9
    environment:
      DATABASES: "${MOODLE_DATABASE:?} ${WORDPRESS_DATABASE:?}"
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:?}
    volumes:
      - mariadb_volume:/var/lib/mysql
      - ./mariadb/create-dbs.sh:/docker-entrypoint-initdb.d/create-dbs.sh
      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  moodle:
    image: bitnami/moodle:4.5
    depends_on:
      - mariadb
    ports:
      - 8081:8080
    volumes:
      - moodle_volume:/bitnami/moodle
      - moodledata_volume:/bitnami/moodledata
    environment:
      MOODLE_DATABASE_HOST: mariadb
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_NAME: ${MOODLE_DATABASE:?}
      MOODLE_DATABASE_USER: ${MARIADB_USERNAME:?}
      MOODLE_DATABASE_PASSWORD: ${MARIADB_PASSWORD:?}

      MOODLE_USERNAME: ${MOODLE_USERNAME:?}
      MOODLE_PASSWORD: ${MOODLE_PASSWORD:?}
      BITNAMI_DEBUG: ${DEBUG:?}

  wordpress:
    image: wordpress:6-apache
    depends_on:
      - mariadb
    ports:
      - 8080:80
    volumes:
      - wordpress_volume:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_PORT: 3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DATABASE:?}
      WORDPRESS_DB_USER: ${MARIADB_USERNAME:?}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD:?}

  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - 8082:8096
    volumes:
      - jellyfin_config_volume:/config
      - jellyfin_cache_volume:/cache
      - ./jellyfin:/media

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    environment:
      HOSTS: "moodle:8080 wordpress:80 jellyfin:8096"
    volumes:
      - ./nginx/create-configs.sh:/docker-entrypoint.d/create-configs.sh
      - ./nginx/template.conf:/etc/nginx/template.conf

volumes:
  mariadb_volume:
  moodle_volume:
  moodledata_volume:
  wordpress_volume:
  jellyfin_config_volume:
  jellyfin_cache_volume:
